name: Github Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: treeform/setup-nim-action@v6
      - name: Install dependencies
        run: |
          nimby install -g bumpy
          nimby install -g chroma
          nimby install -g crunchy
          nimby install -g flatty
          nimby install -g nimsimd
          nimby install -g vmath
          nimby install -g zippy
      - run: nim r tests/tests.nim
